import { useEffect, useMemo, useState } from "react";
import type { AdminAPI, AdminOrder, AdminUser, SystemStatus, Ticket } from "../../lib/api";

type Props = { api: AdminAPI };
const bytes = (value: number) => { if (!Number.isFinite(value) || value <= 0) return "0 B"; const units = ["B", "KB", "MB", "GB", "TB"]; const i = Math.min(Math.floor(Math.log(value) / Math.log(1024)), units.length - 1); return `${(value / 1024 ** i).toFixed(i > 1 ? 2 : 0)} ${units[i]}`; };
const money = (value: number) => `¥${value.toFixed(2)}`;

export function AdminDashboardPage({ api }: Props) {
  const [users, setUsers] = useState<AdminUser[]>([]); const [orders, setOrders] = useState<AdminOrder[]>([]); const [nodes, setNodes] = useState<{ name: string; traffic_upload: number; traffic_download: number; online_count: number }[]>([]); const [tickets, setTickets] = useState<Ticket[]>([]); const [status, setStatus] = useState<SystemStatus | null>(null); const [updated, setUpdated] = useState(new Date()); const [error, setError] = useState("");
  const load = async () => { setError(""); try { const [u, o, n, t, s] = await Promise.all([api.listAdminUsers({ limit: 200, sort_by: "created_at", sort_desc: true }), api.listAdminOrders({ page: 1, page_size: 200, sort_by: "created_at", sort_desc: true }), api.listAdminNodes({ page: 1, page_size: 100 }), api.listAdminTickets({ page: 1, page_size: 100 }), api.getSystemStatus()]); setUsers(u.items); setOrders(o.items); setNodes(n.items.map((item) => ({ name: item.name, traffic_upload: item.traffic_upload, traffic_download: item.traffic_download, online_count: item.online_count }))); setTickets(t.items); setStatus(s); setUpdated(new Date()); } catch (cause) { setError(cause instanceof Error ? cause.message : "仪表盘数据加载失败"); } };
  useEffect(() => { void load(); }, []);
  const now = Date.now(); const day = 86_400_000; const month = now - 30 * day; const prevMonth = now - 60 * day; const paid = orders.filter((o) => o.status === 3 || o.status === 1); const monthOrders = paid.filter((o) => new Date(o.paid_at ?? o.created_at).getTime() >= month); const prevOrders = paid.filter((o) => { const time = new Date(o.paid_at ?? o.created_at).getTime(); return time >= prevMonth && time < month; }); const total = monthOrders.reduce((sum, o) => sum + o.total_amount, 0); const previous = prevOrders.reduce((sum, o) => sum + o.total_amount, 0); const upload = users.reduce((sum, u) => sum + u.traffic_upload, 0); const download = users.reduce((sum, u) => sum + u.traffic_download, 0); const active = users.filter((u) => u.online_count > 0).length; const pendingTickets = tickets.filter((t) => t.status !== 1).length; const pendingCommission = tickets.filter((t) => t.withdrawal?.status === "pending").length; const nodeRank = [...nodes].sort((a, b) => b.traffic_upload + b.traffic_download - a.traffic_upload - a.traffic_download).slice(0, 10);
  const userRank = useMemo(() => [...users].sort((a, b) => b.traffic_used - a.traffic_used).slice(0, 10), [users]);
  return <main className="page-shell admin-dashboard"><header className="page-header"><div><p className="eyebrow">Dashboard</p><h1>仪表盘</h1><p className="muted">业务、节点、用户和队列的运行概览。</p></div><button className="button secondary" onClick={() => void load()}>立即刷新</button></header>{error && <div className="alert error" role="alert">{error}</div>}<section className="dashboard-realtime"><div><h2>实时状态</h2><p className="muted">基于最近一次节点上报的数据</p></div><span className="status-badge enabled">实时 · {updated.toLocaleTimeString("zh-CN", { hour12: false })}</span><div className="dashboard-realtime-grid"><Metric label="在线设备" value={String(nodes.reduce((sum, n) => sum + n.online_count, 0))} hint="按节点心跳汇总" /><Metric label="在线用户" value={String(active)} hint="当前有在线设备" /><Metric label="在线节点" value={String(nodes.filter((n) => n.online_count > 0).length)} hint={`共 ${nodes.length} 个节点`} /></div></section><section className="dashboard-metrics"><Metric label="今日收入" value={money(monthOrders.filter((o) => new Date(o.paid_at ?? o.created_at).toDateString() === new Date().toDateString()).reduce((s, o) => s + o.total_amount, 0))} hint="已支付订单" /><Metric label="月收入" value={money(total)} hint={`较上月 ${previous ? `${((total - previous) / previous * 100).toFixed(1)}%` : "—"}`} /><Metric label="待处理工单" value={String(pendingTickets)} hint={pendingTickets ? "需要处理" : "无待处理工单"} tone={pendingTickets ? "warning" : "good"} /><Metric label="待处理佣金" value={String(pendingCommission)} hint={pendingCommission ? "需要审核" : "无待处理佣金"} tone={pendingCommission ? "warning" : "good"} /><Metric label="月新增用户" value={String(users.filter((u) => new Date(u.created_at).getTime() >= month).length)} hint="最近 30 天" /><Metric label="总用户" value={String(users.length)} hint={`活跃用户 ${active}`} /><Metric label="月上传" value={bytes(upload)} hint={`今日累计 ${bytes(upload)}`} /><Metric label="月下载" value={bytes(download)} hint={`今日累计 ${bytes(download)}`} /></section><div className="dashboard-columns"><Rank title="节点流量排行" items={nodeRank.map((n) => ({ label: n.name, value: bytes(n.traffic_upload + n.traffic_download) }))} /><Rank title="用户流量排行" items={userRank.map((u) => ({ label: u.email, value: bytes(u.traffic_used) }))} /></div><section className="dashboard-queue"><h2>队列状态</h2><div className="dashboard-queue-grid"><Metric label="调度器" value={status?.scheduler.healthy ? "正常" : "异常"} hint={status ? `运行 ${Math.floor(status.uptime_seconds / 60)} 分钟` : "加载中"} tone={status?.scheduler.healthy ? "good" : "danger"} /><Metric label="邮件队列" value={String(status?.mail_queue.pending ?? 0)} hint={`失败 ${status?.mail_queue.failed ?? 0}`} /><Metric label="Telegram 队列" value={String(status?.telegram_queue.pending ?? 0)} hint={`失败 ${status?.telegram_queue.failed ?? 0}`} /><Metric label="近期任务" value={String((status?.mail_queue.sent ?? 0) + (status?.telegram_queue.sent ?? 0))} hint="已发送任务" /></div></section></main>;
}
function Metric({ label, value, hint, tone = "" }: { label: string; value: string; hint?: string; tone?: string }) { return <article className={`overview-metric ${tone}`}><span>{label}</span><strong>{value}</strong>{hint && <small>{hint}</small>}</article>; }
function Rank({ title, items }: { title: string; items: { label: string; value: string }[] }) { const max = Math.max(...items.map((i) => Number.parseFloat(i.value) || 1), 1); return <section className="dashboard-rank"><h2>{title}</h2>{items.length === 0 ? <p className="muted">暂无数据</p> : items.map((item) => <div className="dashboard-rank-row" key={item.label}><span title={item.label}>{item.label}</span><b>{item.value}</b><i style={{ width: `${Math.max(8, (Number.parseFloat(item.value) || 0) / max * 100)}%` }} /></div>)}</section>; }


