package store

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"net"
	"strings"
	"time"

	"github.com/google/uuid"
)

type RegisterUserInput struct {
	Email                string
	PasswordHash         string
	SourceIP             string
	EmailDigest          []byte
	EmailCodeDigest      []byte
	InvitationCodeDigest []byte
}

type RegistrationSessionInput struct {
	TokenHash       string
	CSRFHash        string
	ExpiresAt       time.Time
	AccessTokenHash string
	AccessTokenName string
}

type RegistrationIPLimitError struct {
	RetryAfterSeconds int64
	WindowMinutes     int
}

func (e *RegistrationIPLimitError) Error() string { return ErrRegistrationIPLimited.Error() }
func (e *RegistrationIPLimitError) Unwrap() error { return ErrRegistrationIPLimited }

type registrationPolicy struct {
	stopRegister               bool
	emailVerificationEnabled   bool
	emailWhitelistEnabled      bool
	emailWhitelistSuffixes     []string
	gmailAliasLimitEnabled     bool
	registrationIPLimitEnabled bool
	registrationIPLimitCount   int
	registrationIPLimitMinutes int
	invitationForceEnabled     bool
	invitationNeverExpire      bool
}

func CheckRegistrationEmailPolicy(settings SiteSettings, email string) error {
	return checkRegistrationEmailPolicy(registrationPolicyFromSettings(settings), normalizeEmail(email))
}

func (s *Store) CheckRegistrationIPLimit(ctx context.Context, settings SiteSettings, sourceIP string, now time.Time) error {
	policy := registrationPolicyFromSettings(settings)
	if !policy.registrationIPLimitEnabled {
		return nil
	}
	if !validRegistrationSourceIP(sourceIP) {
		return fmt.Errorf("%w: invalid registration source IP", ErrInvalidInput)
	}
	count, resetAt, err := readRegistrationIPCounter(ctx, s.db, sourceIP)
	if err != nil {
		return err
	}
	return registrationIPLimitError(policy, count, resetAt, now)
}

// RegisterUser checks the registration policy and inserts the account while
// holding the same write lock used by settings updates. This closes the race
// between an administrator stopping registration and a request finishing its
// password hash.
func (s *Store) RegisterUser(ctx context.Context, input RegisterUserInput, now time.Time) (User, error) {
	return s.registerUser(ctx, input, nil, now)
}

// RegisterUserWithSession makes account creation and the first login session
// all-or-nothing. Cookie values are generated by the HTTP layer and only their
// digests cross the storage boundary.
func (s *Store) RegisterUserWithSession(ctx context.Context, input RegisterUserInput, session RegistrationSessionInput, now time.Time) (User, error) {
	accessTokenRequested := session.AccessTokenHash != "" || session.AccessTokenName != ""
	if len(session.TokenHash) != 64 || len(session.CSRFHash) != 64 || !session.ExpiresAt.After(now) ||
		(accessTokenRequested && (!validAccessTokenHash(session.AccessTokenHash) || strings.TrimSpace(session.AccessTokenName) == "" || len([]rune(session.AccessTokenName)) > 80)) {
		return User{}, fmt.Errorf("%w: invalid registration session", ErrInvalidInput)
	}
	return s.registerUser(ctx, input, &session, now)
}

func (s *Store) registerUser(ctx context.Context, input RegisterUserInput, session *RegistrationSessionInput, now time.Time) (User, error) {
	input.Email = normalizeEmail(input.Email)
	if input.Email == "" || len(input.Email) > 320 || input.PasswordHash == "" {
		return User{}, fmt.Errorf("%w: invalid registration", ErrInvalidInput)
	}
	subscriptionToken, err := newSubscriptionToken()
	if err != nil {
		return User{}, err
	}

	defer s.lockWrite()()
	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return User{}, fmt.Errorf("begin registration: %w", err)
	}
	defer tx.Rollback()

	policy, err := readRegistrationPolicy(ctx, tx)
	if err != nil {
		return User{}, fmt.Errorf("read registration policy: %w", err)
	}
	var ipCount int
	var ipResetAt int64
	if policy.registrationIPLimitEnabled {
		if !validRegistrationSourceIP(input.SourceIP) {
			return User{}, fmt.Errorf("%w: invalid registration source IP", ErrInvalidInput)
		}
		ipCount, ipResetAt, err = readRegistrationIPCounter(ctx, tx, input.SourceIP)
		if err != nil {
			return User{}, err
		}
		if err := registrationIPLimitError(policy, ipCount, ipResetAt, now); err != nil {
			return User{}, err
		}
	}
	if err := checkRegistrationEmailPolicy(policy, input.Email); err != nil {
		return User{}, err
	}
	if policy.stopRegister {
		return User{}, ErrRegistrationClosed
	}
	invitation, err := resolveInvitationCodeTx(ctx, tx, input.InvitationCodeDigest, policy.invitationForceEnabled)
	if err != nil {
		return User{}, err
	}
	if policy.emailVerificationEnabled {
		if err := validateRegistrationEmailChallengeTx(ctx, tx, input.EmailDigest, input.EmailCodeDigest, now); err != nil {
			return User{}, err
		}
	}
	result, err := tx.ExecContext(ctx, `
		INSERT INTO users (
			email, password_hash, is_admin, banned, account_kind, uuid, group_id, transfer_enable,
			expired_at, speed_limit, device_limit, subscription_token, invite_user_id, created_at, updated_at
		) VALUES (?, ?, 0, 0, 'human', ?, NULL, 0, NULL, 0, 0, ?, ?, ?, ?)
	`, input.Email, input.PasswordHash, uuid.NewString(), subscriptionToken, nullableInvitationOwner(invitation), now.Unix(), now.Unix())
	if err != nil {
		if strings.Contains(strings.ToLower(err.Error()), "unique") {
			var existing int
			if lookupErr := tx.QueryRowContext(ctx, `SELECT COUNT(*) FROM users WHERE email = ? COLLATE NOCASE`, input.Email).Scan(&existing); lookupErr == nil && existing > 0 {
				return User{}, ErrEmailInUse
			}
		}
		return User{}, fmt.Errorf("insert registered user: %w", err)
	}
	userID, err := result.LastInsertId()
	if err != nil {
		return User{}, fmt.Errorf("read registered user id: %w", err)
	}
	user, err := findUserTx(ctx, tx, userID)
	if err != nil {
		return User{}, err
	}
	if session != nil {
		accessTokenRequested := session.AccessTokenHash != "" || session.AccessTokenName != ""
		if _, err := tx.ExecContext(ctx, `
			INSERT INTO admin_sessions (user_id, token_hash, csrf_hash, expires_at, created_at)
			VALUES (?, ?, ?, ?, ?)
		`, user.ID, session.TokenHash, session.CSRFHash, session.ExpiresAt.Unix(), now.Unix()); err != nil {
			return User{}, fmt.Errorf("create initial registration session: %w", err)
		}
		if accessTokenRequested {
			if _, err := tx.ExecContext(ctx, `
				INSERT INTO access_tokens (user_id, token_hash, name, created_at, updated_at)
				VALUES (?, ?, ?, ?, ?)
			`, user.ID, session.AccessTokenHash, strings.TrimSpace(session.AccessTokenName), now.Unix(), now.Unix()); err != nil {
				return User{}, fmt.Errorf("create initial registration access token: %w", err)
			}
		}
	}
	if policy.registrationIPLimitEnabled {
		nextCount := 1
		if ipResetAt > now.Unix() {
			nextCount = ipCount + 1
		}
		resetAt := now.Add(time.Duration(policy.registrationIPLimitMinutes) * time.Minute).Unix()
		if _, err := tx.ExecContext(ctx, `
			INSERT INTO registration_ip_limits (source_ip, successful_count, reset_at, updated_at)
			VALUES (?, ?, ?, ?)
			ON CONFLICT(source_ip) DO UPDATE SET
				successful_count = excluded.successful_count,
				reset_at = excluded.reset_at,
				updated_at = excluded.updated_at
		`, input.SourceIP, nextCount, resetAt, now.Unix()); err != nil {
			return User{}, fmt.Errorf("record registration IP limit: %w", err)
		}
	}
	if policy.emailVerificationEnabled {
		if err := consumeRegistrationEmailChallengeTx(ctx, tx, input.EmailDigest, now); err != nil {
			return User{}, err
		}
	}
	if invitation != nil && !policy.invitationNeverExpire {
		result, err := tx.ExecContext(ctx, `
			UPDATE invitation_codes SET consumed_at = ?, updated_at = ? WHERE id = ? AND consumed_at IS NULL
		`, now.Unix(), now.Unix(), invitation.id)
		if err != nil {
			return User{}, fmt.Errorf("consume invitation code: %w", err)
		}
		updated, err := result.RowsAffected()
		if err != nil {
			return User{}, fmt.Errorf("count consumed invitation code: %w", err)
		}
		if updated != 1 {
			return User{}, ErrInvitationCodeInvalid
		}
	}
	if err := tx.Commit(); err != nil {
		return User{}, fmt.Errorf("commit registration: %w", err)
	}
	return user, nil
}

type registrationPolicyRow interface {
	QueryRowContext(context.Context, string, ...any) *sql.Row
}

func readRegistrationPolicy(ctx context.Context, query registrationPolicyRow) (registrationPolicy, error) {
	var policy registrationPolicy
	var suffixStorage string
	err := query.QueryRowContext(ctx, `
		SELECT stop_register, email_verify, email_whitelist_enable, email_whitelist_suffix, email_gmail_limit_enable,
		       register_limit_by_ip_enable, register_limit_count, register_limit_expire,
		       invite_force, invite_never_expire
		FROM app_settings WHERE id = 1
	`).Scan(
		&policy.stopRegister, &policy.emailVerificationEnabled, &policy.emailWhitelistEnabled, &suffixStorage, &policy.gmailAliasLimitEnabled,
		&policy.registrationIPLimitEnabled, &policy.registrationIPLimitCount, &policy.registrationIPLimitMinutes,
		&policy.invitationForceEnabled, &policy.invitationNeverExpire,
	)
	if err != nil {
		return registrationPolicy{}, err
	}
	policy.emailWhitelistSuffixes = normalizeEmailWhitelistSuffixes(strings.Split(suffixStorage, ","))
	return policy, nil
}

func registrationPolicyFromSettings(settings SiteSettings) registrationPolicy {
	return registrationPolicy{
		stopRegister: settings.StopRegister, emailVerificationEnabled: settings.EmailVerificationEnabled,
		emailWhitelistEnabled:  settings.EmailWhitelistEnabled,
		emailWhitelistSuffixes: settings.EmailWhitelistSuffixes, gmailAliasLimitEnabled: settings.GmailAliasLimitEnabled,
		registrationIPLimitEnabled: settings.RegistrationIPLimitEnabled,
		registrationIPLimitCount:   settings.RegistrationIPLimitCount,
		registrationIPLimitMinutes: settings.RegistrationIPLimitMinutes,
		invitationForceEnabled:     settings.InvitationForceEnabled,
		invitationNeverExpire:      settings.InvitationNeverExpire,
	}
}

func resolveInvitationCodeTx(ctx context.Context, tx *sql.Tx, codeDigest []byte, force bool) (*activeInvitation, error) {
	if len(codeDigest) == 0 {
		if force {
			return nil, ErrInvitationCodeRequired
		}
		return nil, nil
	}
	if len(codeDigest) != invitationDigestBytes {
		if force {
			return nil, ErrInvitationCodeInvalid
		}
		return nil, nil
	}
	invitation, err := readActiveInvitation(ctx, tx, codeDigest)
	if errors.Is(err, sql.ErrNoRows) {
		if force {
			return nil, ErrInvitationCodeInvalid
		}
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("resolve invitation code: %w", err)
	}
	return &invitation, nil
}

func nullableInvitationOwner(invitation *activeInvitation) any {
	if invitation == nil {
		return nil
	}
	return invitation.ownerID
}

func checkRegistrationEmailPolicy(policy registrationPolicy, email string) error {
	separator := strings.LastIndexByte(email, '@')
	if separator < 1 || separator == len(email)-1 {
		return fmt.Errorf("%w: invalid registration email", ErrInvalidInput)
	}
	localPart, domain := email[:separator], email[separator+1:]
	if policy.emailWhitelistEnabled {
		allowed := false
		for _, suffix := range policy.emailWhitelistSuffixes {
			if domain == suffix {
				allowed = true
				break
			}
		}
		if !allowed {
			return ErrEmailDomainNotAllowed
		}
	}
	if policy.gmailAliasLimitEnabled && (domain == "gmail.com" || domain == "googlemail.com") &&
		(strings.Contains(localPart, ".") || strings.Contains(localPart, "+")) {
		return ErrGmailAliasNotAllowed
	}
	return nil
}

func readRegistrationIPCounter(ctx context.Context, query registrationPolicyRow, sourceIP string) (int, int64, error) {
	var count int
	var resetAt int64
	err := query.QueryRowContext(ctx, `
		SELECT successful_count, reset_at FROM registration_ip_limits WHERE source_ip = ?
	`, sourceIP).Scan(&count, &resetAt)
	if errors.Is(err, sql.ErrNoRows) {
		return 0, 0, nil
	}
	if err != nil {
		return 0, 0, fmt.Errorf("read registration IP limit: %w", err)
	}
	return count, resetAt, nil
}

func registrationIPLimitError(policy registrationPolicy, count int, resetAt int64, now time.Time) error {
	if resetAt <= now.Unix() || count < policy.registrationIPLimitCount {
		return nil
	}
	retryAfter := resetAt - now.Unix()
	if retryAfter < 1 {
		retryAfter = 1
	}
	return &RegistrationIPLimitError{RetryAfterSeconds: retryAfter, WindowMinutes: policy.registrationIPLimitMinutes}
}

func validRegistrationSourceIP(sourceIP string) bool {
	address := net.ParseIP(sourceIP)
	return address != nil && address.String() == sourceIP
}

func (s *Store) PruneExpiredRegistrationIPLimits(ctx context.Context, now time.Time, limit int) (int64, error) {
	if limit < 1 || limit > 1_000 {
		return 0, fmt.Errorf("%w: invalid registration IP prune limit", ErrInvalidInput)
	}
	defer s.lockWrite()()
	result, err := s.db.ExecContext(ctx, `
		DELETE FROM registration_ip_limits
		WHERE source_ip IN (
			SELECT source_ip FROM registration_ip_limits WHERE reset_at <= ? ORDER BY reset_at, source_ip LIMIT ?
		)
	`, now.Unix(), limit)
	if err != nil {
		return 0, fmt.Errorf("prune registration IP limits: %w", err)
	}
	removed, err := result.RowsAffected()
	if err != nil {
		return 0, fmt.Errorf("count pruned registration IP limits: %w", err)
	}
	return removed, nil
}

func findUserTx(ctx context.Context, tx *sql.Tx, userID int64) (User, error) {
	var user User
	err := tx.QueryRowContext(ctx, `
		SELECT id, email, password_hash, is_admin, banned, account_kind, subscription_token
		FROM users WHERE id = ?
	`, userID).Scan(&user.ID, &user.Email, &user.PasswordHash, &user.IsAdmin, &user.Banned, &user.AccountKind, &user.SubscriptionToken)
	if errors.Is(err, sql.ErrNoRows) {
		return User{}, ErrNotFound
	}
	if err != nil {
		return User{}, fmt.Errorf("find registered user: %w", err)
	}
	return user, nil
}
