package store

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/google/uuid"
)

type RegisterUserInput struct {
	Email        string
	PasswordHash string
}

type RegistrationSessionInput struct {
	TokenHash string
	CSRFHash  string
	ExpiresAt time.Time
}

// RegisterUser checks the registration policy and inserts the account while
// holding the same write lock used by settings updates. This closes the race
// between an administrator stopping registration and a request finishing its
// password hash.
func (s *Store) RegisterUser(ctx context.Context, input RegisterUserInput, now time.Time) (User, error) {
	return s.registerUser(ctx, input, nil, now)
}

// RegisterUserWithSession makes account creation and the first login session
// all-or-nothing. Cookie values are generated by the HTTP layer and only their
// digests cross the storage boundary.
func (s *Store) RegisterUserWithSession(ctx context.Context, input RegisterUserInput, session RegistrationSessionInput, now time.Time) (User, error) {
	if len(session.TokenHash) != 64 || len(session.CSRFHash) != 64 || !session.ExpiresAt.After(now) {
		return User{}, fmt.Errorf("%w: invalid registration session", ErrInvalidInput)
	}
	return s.registerUser(ctx, input, &session, now)
}

func (s *Store) registerUser(ctx context.Context, input RegisterUserInput, session *RegistrationSessionInput, now time.Time) (User, error) {
	input.Email = normalizeEmail(input.Email)
	if input.Email == "" || len(input.Email) > 320 || input.PasswordHash == "" {
		return User{}, fmt.Errorf("%w: invalid registration", ErrInvalidInput)
	}
	subscriptionToken, err := newSubscriptionToken()
	if err != nil {
		return User{}, err
	}

	defer s.lockWrite()()
	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return User{}, fmt.Errorf("begin registration: %w", err)
	}
	defer tx.Rollback()

	var stopped bool
	if err := tx.QueryRowContext(ctx, `SELECT stop_register FROM app_settings WHERE id = 1`).Scan(&stopped); err != nil {
		return User{}, fmt.Errorf("read registration policy: %w", err)
	}
	if stopped {
		return User{}, ErrRegistrationClosed
	}
	result, err := tx.ExecContext(ctx, `
		INSERT INTO users (
			email, password_hash, is_admin, banned, account_kind, uuid, group_id, transfer_enable,
			expired_at, speed_limit, device_limit, subscription_token, created_at, updated_at
		) VALUES (?, ?, 0, 0, 'human', ?, NULL, 0, NULL, 0, 0, ?, ?, ?)
	`, input.Email, input.PasswordHash, uuid.NewString(), subscriptionToken, now.Unix(), now.Unix())
	if err != nil {
		if strings.Contains(strings.ToLower(err.Error()), "unique") {
			var existing int
			if lookupErr := tx.QueryRowContext(ctx, `SELECT COUNT(*) FROM users WHERE email = ? COLLATE NOCASE`, input.Email).Scan(&existing); lookupErr == nil && existing > 0 {
				return User{}, ErrEmailInUse
			}
		}
		return User{}, fmt.Errorf("insert registered user: %w", err)
	}
	userID, err := result.LastInsertId()
	if err != nil {
		return User{}, fmt.Errorf("read registered user id: %w", err)
	}
	user, err := findUserTx(ctx, tx, userID)
	if err != nil {
		return User{}, err
	}
	if session != nil {
		if _, err := tx.ExecContext(ctx, `
			INSERT INTO admin_sessions (user_id, token_hash, csrf_hash, expires_at, created_at)
			VALUES (?, ?, ?, ?, ?)
		`, user.ID, session.TokenHash, session.CSRFHash, session.ExpiresAt.Unix(), now.Unix()); err != nil {
			return User{}, fmt.Errorf("create initial registration session: %w", err)
		}
	}
	if err := tx.Commit(); err != nil {
		return User{}, fmt.Errorf("commit registration: %w", err)
	}
	return user, nil
}

func findUserTx(ctx context.Context, tx *sql.Tx, userID int64) (User, error) {
	var user User
	err := tx.QueryRowContext(ctx, `
		SELECT id, email, password_hash, is_admin, banned, account_kind
		FROM users WHERE id = ?
	`, userID).Scan(&user.ID, &user.Email, &user.PasswordHash, &user.IsAdmin, &user.Banned, &user.AccountKind)
	if errors.Is(err, sql.ErrNoRows) {
		return User{}, ErrNotFound
	}
	if err != nil {
		return User{}, fmt.Errorf("find registered user: %w", err)
	}
	return user, nil
}
